### PR TITLE
Add the earliest available Emacs binary 22.3

### PR DESCRIPTION
**Pull request by mlt**

### CODE REVIEW

**Comment by jcs090218** [comment]
Can you add the version to `test.yml` too? Thanks!

**Review by jcs090218 — APPROVED** [review]

**Comment by jcs090218** [comment]
Thank you!

**Comment by mlt** [comment]
Is there any caching of the downloaded Emacs? I have an impression that there is none. Shall I create an issue for it?

**Comment by jcs090218** [comment]
I am not sure what you mean by caching? 🤔 Can you elaborate?

**Comment by mlt** [comment]
I am talking about [actions/cache](https://github.com/actions/cache). So workflows that use your action won't unnecessarily hit Emacs mirrors to re-download same file again and again on new commits. For example, I am using EOL python2 and I don't want to re-download it again but get it extracted from the local GitHub cache instead https://github.com/mlt/Pymacs/actions/caches.

**Comment by jcs090218** [comment]
Oh, okay. I guess there isn't a way to do that yet. 🤔

**Pull request merged**
